// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rookie.AssetManagement.DataAccessor.Data;

#nullable disable

namespace Rookie.AssetManagement.DataAccessor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220803050737_add-table-asset-category")]
    partial class addtableassetcategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "e332664f-7870-4e82-8410-f0b489870948",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "8cbcd895-b323-4af6-aad1-2c7cefcd17c3",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Rookie.AssetManagement.DataAccessor.Entities.Asset", b =>
                {
                    b.Property<string>("AssetCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AssetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AssetState")
                        .HasColumnType("int");

                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("InstalledDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Specification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetCode");

                    b.HasIndex("CategoryID");

                    b.HasIndex("LocationID");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            AssetCode = "PC000001",
                            AssetName = "Dell OptiPlex 3050 Micro",
                            AssetState = 2,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "CPU: 7th Generation Intel Core i3-7100T, Graphics: Intel HD Graphics, RAM: 4GB, Storage: 500GB HDD"
                        },
                        new
                        {
                            AssetCode = "PC000002",
                            AssetName = "Dell OptiPlex 3050 Micro",
                            AssetState = 2,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "CPU: 7th Generation Intel Core i3-7100T, Graphics: Intel HD Graphics, RAM: 4GB, Storage: 500GB HDD"
                        },
                        new
                        {
                            AssetCode = "PC000003",
                            AssetName = "Dell OptiPlex 3050 Micro",
                            AssetState = 2,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "CPU: 7th Generation Intel Core i3-7100T, Graphics: Intel HD Graphics, RAM: 4GB, Storage: 500GB HDD"
                        },
                        new
                        {
                            AssetCode = "PC000004",
                            AssetName = "Dell OptiPlex 3050 Micro",
                            AssetState = 2,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "CPU: 7th Generation Intel Core i3-7100T, Graphics: Intel HD Graphics, RAM: 4GB, Storage: 500GB HDD"
                        },
                        new
                        {
                            AssetCode = "PC000005",
                            AssetName = "Dell OptiPlex 3050 Micro",
                            AssetState = 2,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "CPU: 7th Generation Intel Core i3-7100T, Graphics: Intel HD Graphics, RAM: 4GB, Storage: 500GB HDD"
                        },
                        new
                        {
                            AssetCode = "PC000006",
                            AssetName = "Apple iMac Pro",
                            AssetState = 2,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "CPU: Intel Xeon W, Graphics: AMD Vega 56, Vega 64RAM: 32GB, 64GBStorage: 1TB SSD"
                        },
                        new
                        {
                            AssetCode = "PC000007",
                            AssetName = "Apple iMac Pro",
                            AssetState = 2,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "CPU: Intel Xeon W, Graphics: AMD Vega 56, Vega 64RAM: 32GB, 64GBStorage: 1TB SSD"
                        },
                        new
                        {
                            AssetCode = "PC000008",
                            AssetName = "Apple iMac Pro",
                            AssetState = 2,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "CPU: Intel Xeon W, Graphics: AMD Vega 56, Vega 64RAM: 32GB, 64GBStorage: 1TB SSD"
                        },
                        new
                        {
                            AssetCode = "PC000009",
                            AssetName = "Apple iMac Pro",
                            AssetState = 2,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "CPU: Intel Xeon W, Graphics: AMD Vega 56, Vega 64RAM: 32GB, 64GBStorage: 1TB SSD"
                        },
                        new
                        {
                            AssetCode = "PC000010",
                            AssetName = "Apple iMac Pro",
                            AssetState = 2,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "CPU: Intel Xeon W, Graphics: AMD Vega 56, Vega 64RAM: 32GB, 64GBStorage: 1TB SSD"
                        },
                        new
                        {
                            AssetCode = "PC000011",
                            AssetName = "Dell OptiPlex 3050 Micro",
                            AssetState = 2,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "CPU: 7th Generation Intel Core i3-7100T, Graphics: Intel HD Graphics, RAM: 4GB, Storage: 500GB HDD"
                        },
                        new
                        {
                            AssetCode = "PC000012",
                            AssetName = "Dell OptiPlex 3050 Micro",
                            AssetState = 1,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "CPU: 7th Generation Intel Core i3-7100T, Graphics: Intel HD Graphics, RAM: 4GB, Storage: 500GB HDD"
                        },
                        new
                        {
                            AssetCode = "PC000013",
                            AssetName = "Dell OptiPlex 3050 Micro",
                            AssetState = 2,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "CPU: 7th Generation Intel Core i3-7100T, Graphics: Intel HD Graphics, RAM: 4GB, Storage: 500GB HDD"
                        },
                        new
                        {
                            AssetCode = "PC000014",
                            AssetName = "Dell OptiPlex 3050 Micro",
                            AssetState = 2,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "CPU: 7th Generation Intel Core i3-7100T, Graphics: Intel HD Graphics, RAM: 4GB, Storage: 500GB HDD"
                        },
                        new
                        {
                            AssetCode = "PC000015",
                            AssetName = "Dell OptiPlex 3050 Micro",
                            AssetState = 2,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "CPU: 7th Generation Intel Core i3-7100T, Graphics: Intel HD Graphics, RAM: 4GB, Storage: 500GB HDD"
                        },
                        new
                        {
                            AssetCode = "PC000016",
                            AssetName = "Apple iMac Pro",
                            AssetState = 1,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "CPU: Intel Xeon W, Graphics: AMD Vega 56, Vega 64RAM: 32GB, 64GBStorage: 1TB SSD"
                        },
                        new
                        {
                            AssetCode = "PC000017",
                            AssetName = "Apple iMac Pro",
                            AssetState = 2,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "CPU: Intel Xeon W, Graphics: AMD Vega 56, Vega 64RAM: 32GB, 64GBStorage: 1TB SSD"
                        },
                        new
                        {
                            AssetCode = "PC000018",
                            AssetName = "Apple iMac Pro",
                            AssetState = 1,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "CPU: Intel Xeon W, Graphics: AMD Vega 56, Vega 64RAM: 32GB, 64GBStorage: 1TB SSD"
                        },
                        new
                        {
                            AssetCode = "PC000019",
                            AssetName = "Apple iMac Pro",
                            AssetState = 1,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "CPU: Intel Xeon W, Graphics: AMD Vega 56, Vega 64RAM: 32GB, 64GBStorage: 1TB SSD"
                        },
                        new
                        {
                            AssetCode = "PC000020",
                            AssetName = "Apple iMac Pro",
                            AssetState = 2,
                            CategoryID = "PC",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "CPU: Intel Xeon W, Graphics: AMD Vega 56, Vega 64RAM: 32GB, 64GBStorage: 1TB SSD"
                        },
                        new
                        {
                            AssetCode = "LA000001",
                            AssetName = "Laptop Apple MacBook Pro M1",
                            AssetState = 2,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "Apple M1, RAM 8GB, SSD 256GB"
                        },
                        new
                        {
                            AssetCode = "LA000002",
                            AssetName = "Laptop Apple MacBook Pro M1",
                            AssetState = 2,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "Apple M1, RAM 8GB, SSD 256GB"
                        },
                        new
                        {
                            AssetCode = "LA000003",
                            AssetName = "Laptop Apple MacBook Pro M1",
                            AssetState = 2,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "Apple M1, RAM 8GB, SSD 256GB"
                        },
                        new
                        {
                            AssetCode = "LA000004",
                            AssetName = "Laptop Dell XPS 13 9310",
                            AssetState = 2,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "Intel Core i7 Tiger Lake 1165G7, RAM 16GB LPDDR4X, SSD 1 TB M.2 PCIe"
                        },
                        new
                        {
                            AssetCode = "LA000005",
                            AssetName = "Laptop Dell XPS 13 9310",
                            AssetState = 1,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "Intel Core i7 Tiger Lake 1165G7, RAM 16GB LPDDR4X, SSD 1 TB M.2 PCIe"
                        },
                        new
                        {
                            AssetCode = "LA000006",
                            AssetName = "Laptop Dell XPS 13 9310",
                            AssetState = 5,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "Intel Core i7 Tiger Lake 1165G7, RAM 16GB LPDDR4X, SSD 1 TB M.2 PCIe"
                        },
                        new
                        {
                            AssetCode = "LA000007",
                            AssetName = "Laptop HP Pavilion 15",
                            AssetState = 1,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "Intel Core i5 Tiger Lake 1135G7,  RAM 8GB DDR4, SSD 512 GB NVMe PCIe"
                        },
                        new
                        {
                            AssetCode = "LA000008",
                            AssetName = "Laptop HP Pavilion 15",
                            AssetState = 1,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "Intel Core i5 Tiger Lake 1135G7,  RAM 8GB DDR4, SSD 512 GB NVMe PCIe"
                        },
                        new
                        {
                            AssetCode = "LA000009",
                            AssetName = "Laptop HP Pavilion 15",
                            AssetState = 2,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "Intel Core i5 Tiger Lake 1135G7,  RAM 8GB DDR4, SSD 512 GB NVMe PCIe"
                        },
                        new
                        {
                            AssetCode = "LA000010",
                            AssetName = "Laptop HP Pavilion 15",
                            AssetState = 1,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "Intel Core i5 Tiger Lake 1135G7,  RAM 8GB DDR4, SSD 512 GB NVMe PCIe"
                        },
                        new
                        {
                            AssetCode = "LA000011",
                            AssetName = "Laptop Apple MacBook Pro M1",
                            AssetState = 2,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "Apple M1, RAM 8GB, SSD 256GB"
                        },
                        new
                        {
                            AssetCode = "LA000012",
                            AssetName = "Laptop Apple MacBook Pro M1",
                            AssetState = 2,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "Apple M1, RAM 8GB, SSD 256GB"
                        },
                        new
                        {
                            AssetCode = "LA000013",
                            AssetName = "Laptop Apple MacBook Pro M1",
                            AssetState = 2,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "Apple M1, RAM 8GB, SSD 256GB"
                        },
                        new
                        {
                            AssetCode = "LA000014",
                            AssetName = "Laptop Dell XPS 13 9310",
                            AssetState = 2,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "Intel Core i7 Tiger Lake 1165G7, RAM 16GB LPDDR4X, SSD 1 TB M.2 PCIe"
                        },
                        new
                        {
                            AssetCode = "LA000015",
                            AssetName = "Laptop Dell XPS 13 9310",
                            AssetState = 1,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "Intel Core i7 Tiger Lake 1165G7, RAM 16GB LPDDR4X, SSD 1 TB M.2 PCIe"
                        },
                        new
                        {
                            AssetCode = "LA000016",
                            AssetName = "Laptop Dell XPS 13 9310",
                            AssetState = 5,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "Intel Core i7 Tiger Lake 1165G7, RAM 16GB LPDDR4X, SSD 1 TB M.2 PCIe"
                        },
                        new
                        {
                            AssetCode = "LA000017",
                            AssetName = "Laptop HP Pavilion 15",
                            AssetState = 1,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "Intel Core i5 Tiger Lake 1135G7,  RAM 8GB DDR4, SSD 512 GB NVMe PCIe"
                        },
                        new
                        {
                            AssetCode = "LA000018",
                            AssetName = "Laptop HP Pavilion 15",
                            AssetState = 1,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "Intel Core i5 Tiger Lake 1135G7,  RAM 8GB DDR4, SSD 512 GB NVMe PCIe"
                        },
                        new
                        {
                            AssetCode = "LA000019",
                            AssetName = "Laptop HP Pavilion 15",
                            AssetState = 2,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "Intel Core i5 Tiger Lake 1135G7,  RAM 8GB DDR4, SSD 512 GB NVMe PCIe"
                        },
                        new
                        {
                            AssetCode = "LA000020",
                            AssetName = "Laptop HP Pavilion 15",
                            AssetState = 1,
                            CategoryID = "LA",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "Intel Core i5 Tiger Lake 1135G7,  RAM 8GB DDR4, SSD 512 GB NVMe PCIe"
                        },
                        new
                        {
                            AssetCode = "MO000001",
                            AssetName = "Monitor Dell UltraSharp",
                            AssetState = 2,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "4K, QHD & ultra-high-definition (UHD) monitors"
                        },
                        new
                        {
                            AssetCode = "MO000002",
                            AssetName = "Monitor Dell UltraSharp",
                            AssetState = 2,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "4K, QHD & ultra-high-definition (UHD) monitors"
                        },
                        new
                        {
                            AssetCode = "MO000003",
                            AssetName = "Monitor Dell UltraSharp",
                            AssetState = 1,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "4K, QHD & ultra-high-definition (UHD) monitors"
                        },
                        new
                        {
                            AssetCode = "MO000004",
                            AssetName = "Monitor Dell UltraSharp",
                            AssetState = 2,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "4K, QHD & ultra-high-definition (UHD) monitors"
                        },
                        new
                        {
                            AssetCode = "MO000005",
                            AssetName = "Monitor Dell UltraSharp",
                            AssetState = 2,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "4K, QHD & ultra-high-definition (UHD) monitors"
                        },
                        new
                        {
                            AssetCode = "MO000006",
                            AssetName = "Asus Designo Curve",
                            AssetState = 2,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "Resolution: 3,840 x 1,600px. Brightness: 300 cd/m2"
                        },
                        new
                        {
                            AssetCode = "MO000007",
                            AssetName = "Asus Designo Curve",
                            AssetState = 1,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "Resolution: 3,840 x 1,600px. Brightness: 300 cd/m3"
                        },
                        new
                        {
                            AssetCode = "MO000008",
                            AssetName = "Asus Designo Curve",
                            AssetState = 2,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "Resolution: 3,840 x 1,600px. Brightness: 300 cd/m4"
                        },
                        new
                        {
                            AssetCode = "MO000009",
                            AssetName = "Asus Designo Curve",
                            AssetState = 1,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "Resolution: 3,840 x 1,600px. Brightness: 300 cd/m5"
                        },
                        new
                        {
                            AssetCode = "MO000010",
                            AssetName = "Asus Designo Curve",
                            AssetState = 1,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HCM",
                            Specification = "Resolution: 3,840 x 1,600px. Brightness: 300 cd/m6"
                        },
                        new
                        {
                            AssetCode = "MO000011",
                            AssetName = "Monitor Dell UltraSharp",
                            AssetState = 3,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "4K, QHD & ultra-high-definition (UHD) monitors"
                        },
                        new
                        {
                            AssetCode = "MO000012",
                            AssetName = "Monitor Dell UltraSharp",
                            AssetState = 1,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "4K, QHD & ultra-high-definition (UHD) monitors"
                        },
                        new
                        {
                            AssetCode = "MO000013",
                            AssetName = "Monitor Dell UltraSharp",
                            AssetState = 1,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "4K, QHD & ultra-high-definition (UHD) monitors"
                        },
                        new
                        {
                            AssetCode = "MO000014",
                            AssetName = "Monitor Dell UltraSharp",
                            AssetState = 1,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "4K, QHD & ultra-high-definition (UHD) monitors"
                        },
                        new
                        {
                            AssetCode = "MO000015",
                            AssetName = "Monitor Dell UltraSharp",
                            AssetState = 1,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "4K, QHD & ultra-high-definition (UHD) monitors"
                        },
                        new
                        {
                            AssetCode = "MO000016",
                            AssetName = "Asus Designo Curve",
                            AssetState = 5,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "Resolution: 3,840 x 1,600px. Brightness: 300 cd/m2"
                        },
                        new
                        {
                            AssetCode = "MO000017",
                            AssetName = "Asus Designo Curve",
                            AssetState = 1,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "Resolution: 3,840 x 1,600px. Brightness: 300 cd/m3"
                        },
                        new
                        {
                            AssetCode = "MO000018",
                            AssetName = "Asus Designo Curve",
                            AssetState = 1,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "Resolution: 3,840 x 1,600px. Brightness: 300 cd/m4"
                        },
                        new
                        {
                            AssetCode = "MO000019",
                            AssetName = "Asus Designo Curve",
                            AssetState = 1,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "Resolution: 3,840 x 1,600px. Brightness: 300 cd/m5"
                        },
                        new
                        {
                            AssetCode = "MO000020",
                            AssetName = "Asus Designo Curve",
                            AssetState = 1,
                            CategoryID = "MO",
                            InstalledDay = new DateTime(2021, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationID = "HN",
                            Specification = "Resolution: 3,840 x 1,600px. Brightness: 300 cd/m6"
                        });
                });

            modelBuilder.Entity("Rookie.AssetManagement.DataAccessor.Entities.Category", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = "LA",
                            CategoryName = "Laptop"
                        },
                        new
                        {
                            CategoryID = "MO",
                            CategoryName = "Monitor"
                        },
                        new
                        {
                            CategoryID = "PC",
                            CategoryName = "Personal Computer"
                        });
                });

            modelBuilder.Entity("Rookie.AssetManagement.DataAccessor.Entities.Location", b =>
                {
                    b.Property<string>("LocationID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationID");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationID = "HN",
                            LocationName = "Ha Noi"
                        },
                        new
                        {
                            LocationID = "HCM",
                            LocationName = "Ho Chi Minh"
                        });
                });

            modelBuilder.Entity("Rookie.AssetManagement.DataAccessor.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLogged")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffCode")
                        .HasMaxLength(6)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(6)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LocationID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "195b913a-059f-4855-84ec-11379ec2f527",
                            CreatedDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1989, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailConfirmed = false,
                            FirstName = "Thong",
                            Gender = "F",
                            IsLogged = true,
                            JoinedDate = new DateTime(2015, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nguyen Hoang",
                            LocationID = "HCM",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedUserName = "thongnh",
                            PasswordHash = "AQAAAAEAACcQAAAAEEeGSbiQqRsZtYk/MbSC/ngf0bi8TxHaRZs5ryXUc9MDLa0gAPYDKKsld9LNv1QkPw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NQLC7WE4A7DTOM5DETPA35OHKTOZMMYP",
                            StaffCode = "SD1001",
                            TwoFactorEnabled = false,
                            UserName = "thongnh"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "37b6989f-df67-4a43-ac2c-e4fb94d435eb",
                            CreatedDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1983, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailConfirmed = false,
                            FirstName = "Canh",
                            Gender = "M",
                            IsLogged = false,
                            JoinedDate = new DateTime(2018, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Ho Minh",
                            LocationID = "HCM",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedUserName = "canhhm",
                            PasswordHash = "AQAAAAEAACcQAAAAEFLaHY+NHj00kmdW6xnSNkfgt7JSJIy7XqLbHx1mWbMfi90xld+kNEqZgNE3dRcwzw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NQLC7NG4A7RTOM5DETPA35OHKTOZMMYP",
                            StaffCode = "SD1002",
                            TwoFactorEnabled = false,
                            UserName = "canhhm"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cf3394a6-6e0a-4b88-bf8a-45d7c24e0f15",
                            CreatedDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1987, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailConfirmed = false,
                            FirstName = "Khanh",
                            Gender = "F",
                            IsLogged = false,
                            JoinedDate = new DateTime(2020, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nguyen Tran Bao",
                            LocationID = "HN",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedUserName = "khanhntb",
                            PasswordHash = "AQAAAAEAACcQAAAAECbXOhIi3rIij2ahhKAaSoNX6oirQwaxFnQEzGe2ocHlcvwsUoX6hijzC2CZx78myA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NQLC7NG4A7DTYM5DETPA35OHKTOZMMYP",
                            StaffCode = "SD1003",
                            TwoFactorEnabled = false,
                            UserName = "khanhntb"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c873c5ad-afc8-4818-b4c5-1a7b373791d3",
                            CreatedDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1983, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailConfirmed = false,
                            FirstName = "Sang",
                            Gender = "F",
                            IsLogged = false,
                            JoinedDate = new DateTime(2018, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nguyen Vinh",
                            LocationID = "HN",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedUserName = "sangnv",
                            PasswordHash = "AQAAAAEAACcQAAAAEET+jHm2Uh7XBCgd+V/Y27K7uPTat8sYOarM6Ih2mxnWGkCoP2dqYXuVmnnhRidMkA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NQLC7NG4A7DTOJ5DETPA35OHKTOZMMYP",
                            StaffCode = "SD1005",
                            TwoFactorEnabled = false,
                            UserName = "sangnv"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "20ef6db7-0400-4786-840f-c88730d2466d",
                            CreatedDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1980, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailConfirmed = false,
                            FirstName = "Nhut",
                            Gender = "M",
                            IsLogged = true,
                            JoinedDate = new DateTime(2020, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Tran Minh",
                            LocationID = "HN",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedUserName = "nhattm",
                            PasswordHash = "AQAAAAEAACcQAAAAEPXB6TA3dO0IyOXbdhRJGw9zU4yfR1OxbIivHt26l6mfcVc1GqRg94bVMDsNPq5uEQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NQLC7NG4R7DTOM5DETPA35OHKTOZMMYP",
                            StaffCode = "SD1006",
                            TwoFactorEnabled = false,
                            UserName = "nhattm"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d8ad75e3-b08a-4ba7-9b66-b4b8a63b9144",
                            CreatedDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1987, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailConfirmed = false,
                            FirstName = "Van",
                            Gender = "F",
                            IsLogged = true,
                            JoinedDate = new DateTime(2016, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nguyen Ngoc Gia",
                            LocationID = "HN",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedUserName = "vannng",
                            PasswordHash = "AQAAAAEAACcQAAAAEMwcCuowgQR9gykwHj2bHLeezahteoMikJVUq7+ynOns4ue4Hoxwxnp+jQaY/F15+g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NQLC7NG4A7DTOM5DHTPA35OHKTOZMMYP",
                            StaffCode = "SD1007",
                            TwoFactorEnabled = false,
                            UserName = "Vannng"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c1a6f3dd-3b87-4d8c-99dd-b68fe8d5be5e",
                            CreatedDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1987, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailConfirmed = false,
                            FirstName = "Thang",
                            Gender = "F",
                            IsLogged = false,
                            JoinedDate = new DateTime(2016, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nguyen Viet",
                            LocationID = "HN",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedUserName = "thangnv",
                            PasswordHash = "AQAAAAEAACcQAAAAEGaGTItPiwO6AZRTRRvoDvcIkoR9cCG8a1fMuodzpt/NATHNYQV7FSDd6sYltlHzVA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NQLC7NG4A7DTOM5DETPA35OMKTOZMMYP",
                            StaffCode = "SD1008",
                            TwoFactorEnabled = false,
                            UserName = "thangnv"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "26b2fe1f-6809-4b86-9cd4-5f34f5598346",
                            CreatedDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1984, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailConfirmed = false,
                            FirstName = "Toan",
                            Gender = "M",
                            IsLogged = false,
                            JoinedDate = new DateTime(2017, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Le Hang",
                            LocationID = "HCM",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedUserName = "toanlh",
                            PasswordHash = "AQAAAAEAACcQAAAAEJzPO3i2VHUyZ5rLFnhBTgggv2OjHgjJwjS1IU2PZ1CGfbhkjgiwJTDVjaWLReyCmw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NQLC7NG4A7DTOM5DETPA35OHKTOZBMYP",
                            StaffCode = "SD1009",
                            TwoFactorEnabled = false,
                            UserName = "toanlh"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a2e7dc12-70b9-417d-a41d-d6afdd0e6249",
                            CreatedDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1981, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailConfirmed = false,
                            FirstName = "Quy",
                            Gender = "M",
                            IsLogged = false,
                            JoinedDate = new DateTime(2017, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bui Duy",
                            LocationID = "HCM",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedUserName = "quybd",
                            PasswordHash = "AQAAAAEAACcQAAAAEDvX8x78axkjbLBOhHAIQMYb2f8gUuXi431FrnijJ/xvgNDx7sep5nKkAxwgSKQtUA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NQLC7NG4A7DTOM5DETPA35OHKTOZMMYP",
                            StaffCode = "SD1010",
                            TwoFactorEnabled = false,
                            UserName = "quybd"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0ae322c3-9114-494a-8715-11586bc4aeac",
                            CreatedDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1986, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailConfirmed = false,
                            FirstName = "Phuong",
                            Gender = "F",
                            IsLogged = false,
                            JoinedDate = new DateTime(2018, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Vo Hoang",
                            LocationID = "HCM",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NormalizedUserName = "phuongvh",
                            PasswordHash = "AQAAAAEAACcQAAAAEHnFlCqgP9XE/y9ydhjLyk9x8Pw/kKzUx+lyOlnJejE7neO2z+ZChzK/Ee6me00W1g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NQLC7NG4A7DTOM5DETPA35OHKTOWMMYP",
                            StaffCode = "SD1011",
                            TwoFactorEnabled = false,
                            UserName = "phuongvh"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Rookie.AssetManagement.DataAccessor.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Rookie.AssetManagement.DataAccessor.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rookie.AssetManagement.DataAccessor.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Rookie.AssetManagement.DataAccessor.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rookie.AssetManagement.DataAccessor.Entities.Asset", b =>
                {
                    b.HasOne("Rookie.AssetManagement.DataAccessor.Entities.Category", "Category")
                        .WithMany("Assets")
                        .HasForeignKey("CategoryID");

                    b.HasOne("Rookie.AssetManagement.DataAccessor.Entities.Location", "Location")
                        .WithMany("Assets")
                        .HasForeignKey("LocationID");

                    b.Navigation("Category");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Rookie.AssetManagement.DataAccessor.Entities.User", b =>
                {
                    b.HasOne("Rookie.AssetManagement.DataAccessor.Entities.Location", "Location")
                        .WithMany("Users")
                        .HasForeignKey("LocationID");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Rookie.AssetManagement.DataAccessor.Entities.Category", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("Rookie.AssetManagement.DataAccessor.Entities.Location", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
